### ISSUE TITLE
registro automotor

### ISSUE THREAD

**Issue by mpoledo** [vlasvlasvlas/decreto-gpt#1]
como se reforma el registro automotor?

**Comment by vlasvlasvlas** [comment]
mis disculpas x la demora!
ya se subió la respuesta al final del notebook: https://github.com/vlasvlasvlas/decreto-gpt/blob/main/analisis_con_respuestas.ipynb

la resp que dió:

# Pregunta
profundizame lo relacionado cóomo se reforma el registro automotor. Sé preciso y completo en tu respuesta.

# Respuesta
El decreto de necesidad de urgencia propuesto contempla una serie de reformas al sistema de registro automotor en Argentina que busca modernizar y simplificar los procedimientos asociados con la inscripción y transferencia de vehículos, así como mejorar la eficiencia en todo el sistema de registro de propiedad del automotor.


Las reformas propuestas al registro automotor incluyen:

Las reformas propuestas al registro automotor incluyen:

1.  Inscripciones y trámites digitales:
    
    -   Implementación de un servicio de inscripción remoto bajo jurisdicción nacional, establecido por la Dirección Nacional.
    -   Posibilidad de realizar inscripciones o anotaciones de manera electrónica.
    -   Facilitación de un acceso público al registro electrónico para la revisión de información.
2.  Actualización de documentos y certificados:
    
    -   Entrega de cédulas de identificación del automotor, las cuales podrán ser emitidas de forma digital y tendrán la misma validez que las físicas.
    -   Modificación al artículo 20, en el que se establece que juntamente con cada inscripción o transferencia de dominio, se expedirá un título del automotor y se entregará al titular una o más cédulas de identificación de este.
3.  Libertad en la transferencia de vehículos:
    
    -   Supresión de restricciones y limitaciones para la inscripción o transferencia de automotores asociadas a multas o patentes, asegurando que la existencia de deudas no impida estas operaciones.
    -   Empoderamiento de los comerciantes habituales en la compraventa de automotores para inscribir los vehículos adquiridos a su nombre en el registro.
4.  Modificaciones a la retención de documentos:
    
    -   Establecimiento de que las cédulas, las licencias para conducir y el comprobante de pago de patente son los únicos requerimientos para la circulación legal de los vehículos.
    -   Prohibición de la retención de estos documentos por autoridades locales, salvo en casos de denuncia de hurto o robo u orden judicial.
5.  Responsabilidad y denuncia de tradición:
    
    -   Cambio en la responsabilidad por los tributos asociados al automotor, desligando al titular transmitente desde la fecha de denuncia de tradición.
6.  Modificación de los procedimientos para automotores armados fuera de fábrica:
    
    -   Requisitos claros y simplificados para inscribir automotores no fabricados industrialmente, contando con autorización del Organismo de Aplicación.
7.  Cláusula Transitoria:
    
    -   Obligación de la Dirección Nacional de poner en marcha su registro remoto a más tardar el 2 de mayo de 2024.


Estas medidas tienen el propósito de agilizar y favorecer la automatización de los trámites del registro automotor, facilitando el acceso a la información y mejorando la gestión administrativa para propietarios, compradores y vendedores de automotores. Estos cambios representarían un ajuste significativo en la operación del registro automotor, reduciendo la burocracia y propiciando mayor transparencia.
